### ISSUE TITLE
Fill the need 7 and admin panel

### ISSUE THREAD

**Issue by Harpreet-9504** [Harpreet-9504/BLKsearch#25]
Use validation for these as user is required to choose one of these two checkboxes
"Please select one option."
![image](https://user-images.githubusercontent.com/66643324/127962676-6291c3e2-8b0c-422b-ab77-d3effbfc07f2.png)

also show this info on admin panel as well, admin should know who has registered this business 
make a column "Registered By" 
"Business Owner" - if user select this checkbox
![image](https://user-images.githubusercontent.com/66643324/127962952-ca8a294a-d708-4ecb-b74a-06ea97579898.png)
or "Recommended" if user select this checkbox
![image](https://user-images.githubusercontent.com/66643324/127963384-387bd9cf-0c6c-4cc1-80ce-bf40edb57b2e.png)

**Comment by Harpreet-9504** [comment]
NOt done for both website and admin panel

**Comment by Davinder218** [comment]
admin panel me action me eye se business information me registerd by show kiya hai.
